### ISSUE TITLE
Preprocessor stores css in STATIC_ROOT for development as well?

### ISSUE THREAD

**Issue by goanpeca** [jrief/django-sekizai-processors#1]
Hi Jacob, thanks for this very useful addition to the django family :)

I am probably doing something wrong so I ask just to be sure. I am testing you processor with a current project. I am working locally and the file is being processed and converted, but it is also being stored in the STATIC_ROOT. So the css is parsed but when I click on the link in the page source code (`<link href="/static/css/base-style.css" rel="stylesheet" type="text/css" />`), it reports a 404 error. 

My static conf is:

```python
STATIC_ROOT (`public/static`)
STATIC_URL = '/static/'
```

I have not used django-cms for such a long time, but I normally only get files dumped in my STATIC_ROOT, unless I ran collectstatic, so I do not know if this is a normal behavior, and if it is, how would I get it to work for local development?

Cheers

**Comment by jrief** [comment]
You don't need django-cms, only django-sekizai.
And the link must be inside a ``{% addtoblock "css" preprocessor "..." %}<link href="...file.scss" ... />{% endaddtoblock %}``.

Did you do that?

**Comment by goanpeca** [comment]
Hi, I meant I am new to django (not to python) and I am also new to django-cms, and I am using it for a project right now.

I used as the example

`{% addtoblock "css" preprocessor "sekizai_processors.sass_preprocessor.compilescss" %}<link href="{% static 'css/styles.scss' %}" rel="stylesheet" type="text/css" />{% endaddtoblock %}`

I stored the raw scss file in a global static folder where I also have other assets (fancyboxes .. ythings like that)

And when rendering the page it transforms to

`<link href="/static/css/mystyle.css" rel="stylesheet" type="text/css" />`

And it saves two new files in `public/static/css` which is the STATIC_ROOT, but on development apparently this is not resolved?

I am working locally for the moment (linux...) and when clicking on the source of the rendered `<link ...` it raises a 404 page

**Comment by jrief** [comment]
During development, the compiled file is placed into STATIC_ROOT in order to not pollute your local  static/css/ folder with auto-generated files.
Therefore assure, that in your settings STATIC_ROOT points to an accessible folder and that a finder finds that file. I'm currently using the CompressorFinder.
Please retest with
```
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
```

sorry, I forgot to add this to the docs.

**Comment by goanpeca** [comment]
Hi, indeed that solved the problem, but now another question is:

The file should regenerate (if younger) only when restarting the local development server? or any time a page is refreshed (and the scss has time stamps younger that the generated css)? I am only getting a new file if I delete the previously generated one(s)...

Did you mean `load sekizai_tags` in  https://github.com/jrief/django-sekizai-processors#in-your-django-templates ?

**Comment by jrief** [comment]
No it should regenerate whenever any of the depending *.scss files changes and the timestamps are younger. But this is done, when parsing the template.

> I am only getting a new file if I delete the previously generated one(s)...

make sure, that no cache is in between, otherwise the template is served from the cache.

If your settings has something such as:
```
MIDDLEWARE_CLASSES = (
    'django.middleware.cache.UpdateCacheMiddleware',
   ...
    'django.middleware.cache.FetchFromCacheMiddleware',
)
```
you'd have to restart the server after each change - presumably not what you want.

> Did you mean load sekizai_tags

Sure! Typo hell.

**Comment by goanpeca** [comment]
Great :), all fixed now. Thanks for the quick answers

**Comment by jrief** [comment]
Early adopters fix the first bugs.
Thanks for reporting and please rate this project.

**Comment by jrief** [comment]
Sekizai is not required anymore.
This now is a stand-alone project and has been renamed to django-sass-processor.
It now should aim for a much bigger audience.
Sorry for the inconvenience having broken the API.

**Comment by goanpeca** [comment]
Great :), indeed is for the best, my setup is updated :+1:  thanks for the headsup and keep up the great work
